### ISSUE TITLE
Checklist for going public

### ISSUE THREAD

**Issue by AB-xdev** [xdev-software/csapi#8]
- [x] Use organization secrets (Fixes "Organization secrets can only be used by public repositories on your plan")
- [x] Build with Java 17
- [x] License
- [x] Check Sourcepath for JavaDoc
- [x] Migration guide
- [x] Create a release
- [x] Enable branch protection
- [x] Enable GH-pages
